# Exception



### 1. java 예외처리

1. 오류

컴파일 오류는 잡기가 쉽지만 **런타임 에러**는 잡기가 어렵다.

이러한 런타임 에러는 두 종류로 보고 있습니다.

**에러(Error)**와 **예외(Exception)**

- 에러 : 프로그램이 **코드로 복구될 수 없는 오류**를 의미
  - 메모리 부족과 같은 오류
    - `OutOfMemoryError`, `StackOverFlowError` 등...
- 예외 : 프로그래머가 직접 예측하여 막을 수 있는 **처리가능한 오류**
  - 예외는 또 두가지 종류로 나눠진다.
    - 컴파일 에러 : 컴파일시 발견되는 예외
    - **런타임 에러** : 런타임시 발견되는 예외, 런타임 에러를 우리(프로그래머)가 **예측하여 처리**해줘야함



2. 예외 처리

java는 기본적으로 `try ... catch`, `throw` 구문을 사용하여 오류를 처리한다.

<img src="https://blog.kakaocdn.net/dn/bZDGhx/btq1I7rwySp/RsGRdGQ7TmuayB5jTi5CTK/img.png" alt="img" style="zoom:67%;" />

첫번째로 `try ... catch ... finally`라는 키워드로 예외를 처리할 수 있습니다.

예외가 발생 했을 때, 메소드를 호출한 곳으로 예외를 던질 수 있습니다.

중요한 포인트는 자바에서 모든 예외는 `Exception`이라는 클래스를 상속받습니다.

예외 처리 방식은 아래와 같다.

```java
try{
	//예외가 발생될만한 코드
}catch(FileNotFoundException e){	//FileNotFoundException이 발생했다면

}catch(IOException e){ //IOException이 발생했다면

}catch(Exception e){	//Exception이 발생했다면

}finally{	
	///어떤 예외가 발생하던 말던 무조건 실행
}
```

try 블록에서 예외가 발생할만한 코드를 작성하고 catch에 해당하는 예외가 발생했을 때 처리되는 코드를 작성합니다.

여러 개의 catch를 작성할 수 있지만 catch의 순서가 존재합니다. 즉, 자식 예외를 먼저 작성하고 부모 예외를 나중에 작성해야 합니다. 



두번째로 `throws`를 사용하여 예외를 그냥 던질 수 있습니다. 

즉, 예외를 여기서 처리하지 않을테니 나를 불러다가 쓰는 녀석에게 에러 처리를 전가하겠다는 의미이며 코드를 짜는 사람이 이 선언부를 보고 어떤 예외가 발생할 수 있는지도 알게 해줍니다. 



```java
public class Main {

  public static void divide(int a, int b) throws ArithmeticException{

    if(b == 0){
      throw new ArithmeticException("0으로 나눌 수 없다.");
    }

    int ans = a / b;

    System.out.println(ans);

  }

  public static void main(String[] args) {

    int a = 10;
    int b = 0;

    try {
      divide(a, b);
    } catch (ArithmeticException e) {
      System.out.println("다음과 같은 에러가 발생하였다." + e.getMessage());
      e.printStackTrace();
    }

    System.out.println("프로그램 종료");
  }
}
```

<img src="img/image-20220409051641066.png" alt="image-20220409051641066" style="zoom:50%;" />



아래와 같이 예외를 던질 수 있다.

```java
throw 예외객체
//ex) throw new Exception("예외 발생!");
```

던지면 위 메소드를 호출한 곳에서 예외를 처리를 할 수가 있다.

위 코드에서 `divide()` 메소드에서 예외가 발생하였고 `throw`를 호출한 `main`에 던졌다.

예외 객체를 전달받은 `main`에서 `try ... catch`를 하여 예외를 캐치하고 `catch`블록을 실행한다. 

그 후 정상적으로 나머지 코드를 실행한 후 종료가 된다.

핵심은 `throw new ArithmeticException("0으로 나눌 수 없다.");`에서 객체를 생성하여 호출한 메소드로 `throw`(던지는 것)하고 catch하는 것이다. 



### 2. Spring boot 예외처리

Spring Boot에서 예외 처리를 하는 방법은 다양하다. 그 중 대표적인 예외 처리 방법은 아래와 같다.

- Controller에서 ExceptionHandler 정의
- ControllerAdvice에 ExceptionHandler 정의
- Exception에 ResponseStatus 어노테이션 추가



1. DispatcherServlet

   SpringBoot에서는 요청이 들어오면 dispatcherServlet에 의해서 적합한 컨트롤러에 위임을 하는 역할을 하고 있다.

   그러기 때문에 Spring Boot에서 dispatcherServlet이 `try ... catch`문을 이용하여 예외를 처리를 한다.

   ```java
   public class DispatcherServlet {
     protected void doDispatch(...) throws Exception {
       // ...
       try {
         ModelAndView mv = null;
         Exception dispatchException = null;
   
         try {
             // Controller 로직 실행 (핸들러를 찾고, 해당 로직을 실행)
         } catch (Exception ex) {
           dispatchException = ex;
         }
         // Dispatch 결과 처리 (예외 처리도 여기서 진행)
         processDispatchResult(...,dispatchException);
       } catch {...}
       // ...
     }
   }
   ```

   



2. 예외 처리 방법

   `HandlerExceptionResolver.resolveExceptionHandler()`에서 어떤 `ExceptionResolver`를 택할지 결정한다. 다음의 3가지의 `ExceptionResolver`가 존재한다.

   - `ExceptionHandlerExceptionResolver`
   - `ResponseStatusExceptionResolver`
   - `DefaultHandlerExceptionResolver`

   이름에서 유추할 수 있듯이, `ExceptionHandler`로 정의한 경우에는 `ExceptionHandlerExceptionResolver`, 

   `ResponseStatus`로 정의한 경우 `ResponseStatusExceptionResolver`로 처리한다.

   ```java
   public class HandlerExceptionResolverComposite {
     public ModelAndView resolveException(
       HttpServletRequest request, HttpServletResponse response, @Nullable Object handler,
       Exception ex) {
   
       if (this.resolvers != null) {
         for (HandlerExceptionResolver handlerExceptionResolver : this.resolvers) {
           ModelAndView mav = handlerExceptionResolver.resolveException(request, response, handler, ex);
           if (mav != null) {
             return mav;
           }
         }
       }
       return null;
     }
   }
   ```

   